### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Haze-sh** [bachya/aiolinkding#34]
**Describe the bug**
*client.bookmarks.async.create()* returns Timeout error. Tried using connection pooling but returns *Server disconnected* when creating large number of bookmarks.
LD_REQUEST_TIMEOUT variable is used with timeout 3600.

**To Reproduce**
Use to create large number of bookmarks, usually stops after uploading about 60 bookmarks.

**Expected behavior**
Expects to upload all bookmarks.

**Comment by Haze-sh** [comment]
Thanks @bachya for the response!

I made changes to my code and it gave the error *aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected* after uploading 100 bookmarks.

I also used your script and just tweaked the number of bookmarks to more than 100 (I used 10000) and it gave the same error.

Is this is an expected behaviour? Or there is something I am missing?

**Comment by bachya** [comment]
If I modify my example to create 10,000 bookmarks simultaneously, I get a comparable error:

```
Traceback (most recent call last):
  File "/Users/bachya/.virtualenvs/aiolinkding/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 581, in write_bytes
    await self.body.write(writer)
  File "/Users/bachya/.virtualenvs/aiolinkding/lib/python3.11/site-packages/aiohttp/payload.py", line 247, in write
    await writer.write(self._value)
  File "/Users/bachya/.virtualenvs/aiolinkding/lib/python3.11/site-packages/aiohttp/http_writer.py", line 116, in write
    self._write(chunk)
  File "/Users/bachya/.virtualenvs/aiolinkding/lib/python3.11/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

`ConnectionResetError` seems to indicate a server issue—from [this SO post](https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean/1434506#1434506):

> It's fatal. The remote server has sent you a RST packet, which indicates an immediate dropping of the connection, rather than the usual handshake. This bypasses the normal half-closed state transition. I like [this description](http://everything2.com/title/Connection+reset+by+peer):
>
>> "Connection reset by peer" is the TCP/IP equivalent of slamming the phone back on the hook. It's more polite than merely not replying, leaving one hanging. But it's not the FIN-ACK expected of the truly polite TCP/IP converseur.

So, it sounds like linkding is closing off responses too early when facing a high number of requests; therefore, the issue probably lies within linkding. I recommend you post an issue there (feel free to reference this one).
